const iconsNames = [
  "hourglass",
  "shopping-fill",
  "bulb",
  "skin-fill",
  "experiment",
  "video-fill",
  "bell",
  "sound-fill",
  "trophy",
  "bulb-fill",
  "rest",
  "bell-fill",
  "USB",
  "filter-fill",
  "skin",
  "fire-fill",
  "home",
  "funnel plot-fill",
  "bank",
  "gift-fill",
  "filter",
  "hourglass-fill",
  "funnel plot",
  "home-fill",
  "like",
  "trophy-fill",
  "unlike",
  "location-fill",
  "unlock",
  "cloud-fill",
  "lock",
  "customerservice-fill",
  "customerservice",
  "experiment-fill",
  "flag",
  "eye-fill",
  "money collect",
  "like-fill",
  "medicinebox",
  "lock-fill",
  "shop",
  "unlike-fill",
  "rocket",
  "star-fill",
  "shopping",
  "unlock-fill",
  "folder",
  "alert-fill",
  "folder-open",
  "api-fill",
  "folder-add",
  "highlight-fill",
  "deployment unit",
  "phone-fill",
  "account book",
  "edit-fill",
  "contacts",
  "pushpin-fill",
  "carry out",
  "rocket-fill",
  "calendar-check",
  "thunderbolt-fill",
  "calendar",
  "tag-fill",
  "scan",
  "wrench-fill",
  "select",
  "tags-fill",
  "box plot",
  "bank-fill",
  "build",
  "camera-fill",
  "sliders",
  "error-fill",
  "laptop",
  "crown-fill",
  "barcode",
  "mail-fill",
  "camera",
  "car-fill",
  "cluster",
  "printer-fill",
  "gateway",
  "shop-fill",
  "car",
  "setting-fill",
  "printer",
  "USB-fill",
  "read",
  "golden-fill",
  "cloud-server",
  "build-fill",
  "cloud-upload",
  "box plot-fill",
  "cloud",
  "sliders-fill",
  "cloud-download",
  "alibaba",
  "cloud-sync",
  "ant design",
  "video",
  "ant-cloud",
  "notification",
  "behance",
  "sound",
  "google plus",
  "radar chart",
  "medium",
  "qrcode",
  "google",
  "fund",
  "IE",
  "image",
  "amazon",
  "mail",
  "slack",
  "table",
  "alipay",
  "id card",
  "taobao",
  "credit card",
  "zhihu",
  "heart",
  "HTML",
  "block",
  "linkedin",
  "error",
  "yahoo",
  "star",
  "facebook",
  "gold",
  "skype",
  "heat map",
  "CodeSandbox",
  "wifi",
  "chrome",
  "attachment",
  "codepen",
  "edit",
  "aliwangwang",
  "key",
  "apple",
  "api",
  "android",
  "disconnect",
  "sketch",
  "highlight",
  "Gitlab",
  "monitor",
  "dribbble",
  "link",
  "instagram",
  "man",
  "reddit",
  "percentage",
  "windows",
  "pushpin",
  "yuque",
  "phone",
  "Youtube",
  "shake",
  "Gitlab-fill",
  "tag",
  "dropbox",
  "wrench",
  "dingtalk",
  "tags",
  "android-fill",
  "scissor",
  "apple-fill",
  "mr",
  "HTML-fill",
  "share",
  "windows-fill",
  "branches",
  "QQ",
  "fork",
  "twitter",
  "shrink",
  "skype-fill",
  "arrawsalt",
  "weibo",
  "vertical right",
  "yuque-fill",
  "vertical left",
  "Youtube-fill",
  "right",
  "yahoo-fill",
  "left",
  "wechat-fill",
  "up",
  "chrome-fill",
  "down",
  "alipay-circle-fill",
  "fullscreen",
  "aliwangwang-fill",
  "fullscreen-exit",
  "behance-circle-fill",
  "doubleleft",
  "amazon-circle-fill",
  "double right",
  "codepen-circle-fill",
  "arrowright",
  "CodeSandbox-circle-f",
  "arrowup",
  "dropbox-circle-fill",
  "arrowleft",
  "github-fill",
  "arrowdown",
  "dribbble-circle-fill",
  "upload",
  "google plus-circle-f",
  "colum-height",
  "medium-circle-fill",
  "vertical-align-botto",
  "QQ-circle-fill",
  "vertical-align-middl",
  "IE-circle-fill",
  "totop",
  "google-circle-fill",
  "vertical-align-top",
  "dingtalk-circle-fill",
  "download",
  "sketch-circle-fill",
  "sort-descending",
  "slack-circle-fill",
  "sort-ascending",
  "twitter-circle-fill",
  "fall",
  "taobao-circle-fill",
  "swap",
  "weibo-circle-fill",
  "stock",
  "zhihu-circle-fill",
  "rise",
  "reddit-circle-fill",
  "indent",
  "alipay-square-fill",
  "outdent",
  "dingtalk-square-fill",
  "menu",
  "CodeSandbox-square-f",
  "unordered list",
  "behance-square-fill",
  "ordered list",
  "amazon-square-fill",
  "align-right",
  "codepen-square-fill",
  "align-center",
  "dribbble-square-fill",
  "align-left",
  "dropbox-square-fill",
  "pic-center",
  "facebook-fill",
  "pic-right",
  "google plus-square-f",
  "pic-left",
  "google-square-fill",
  "bold",
  "instagram-fill",
  "font-colors",
  "IE-square-fill",
  "exclaimination",
  "medium-square-fill",
  "font-size",
  "linkedin-fill",
  "CI",
  "infomation",
  "QQ-square-fill",
  "Dollar",
  "line-height",
  "reddit-square-fill",
  "compass",
  "strikethrough",
  "twitter-square-fill",
  "close-circle",
  "underline",
  "sketch-square-fill",
  "frown",
  "number",
  "slack-square-fill",
  "info-circle",
  "italic",
  "taobao-square-fill",
  "left-circle",
  "code",
  "weibo-square-fill",
  "down-circle",
  "column-width",
  "zhihu-square-fill",
  "EURO",
  "check",
  "zoom out",
  "copyright",
  "ellipsis",
  "apartment",
  "minus-circle",
  "dash",
  "audio",
  "meh",
  "close",
  "audio-fill",
  "plus-circle",
  "enter",
  "robot",
  "play-circle",
  "line",
  "zoom in",
  "question-circle",
  "minus",
  "robot-fill",
  "Pound",
  "question",
  "bug-fill",
  "right-circle",
  "rollback",
  "bug",
  "smile",
  "small-dash",
  "audio static",
  "trademark",
  "pause",
  "comment",
  "time-circle",
  "bg-colors",
  "signal-fill",
  "time out",
  "crown",
  "verified",
  "earth",
  "drag",
  "shortcut-fill",
  "YUAN",
  "desktop",
  "videocamera add",
  "up-circle",
  "gift",
  "switch user",
  "warning-circle",
  "stop",
  "whatsapp",
  "sync",
  "fire",
  "appstore add",
  "transaction",
  "thunderbolt",
  "caret-down",
  "undo",
  "check-circle-fill",
  "backward",
  "redo",
  "left-circle-fill",
  "caret-up",
  "reload",
  "down-circle-fill",
  "caret-right",
  "reload time",
  "minus-circle-fill",
  "caret-left",
  "message",
  "close-circle-fill",
  "fast-backward",
  "dashboard",
  "info-circle-fill",
  "forward",
  "issues close",
  "up-circle-fill",
  "fast-forward",
  "poweroff",
  "right-circle-fill",
  "search",
  "logout",
  "plus-circle-fill",
  "retweet",
  "pie chart",
  "question-circle-fill",
  "login",
  "setting",
  "EURO-circle-fill",
  "step-backward",
  "eye",
  "frown-fill",
  "step-forward",
  "location",
  "copyright-circle-fil",
  "swap-right",
  "edit-square",
  "CI-circle-fill",
  "swap-left",
  "export",
  "compass-fill",
  "woman",
  "save",
  "Dollar-circle-fill",
  "plus",
  "Import",
  "poweroff-circle-fill",
  "eye close-fill",
  "app store",
  "meh-fill",
  "eye-close",
  "close-square",
  "play-circle-fill",
  "clear",
  "down-square",
  "Pound-circle-fill",
  "collapse",
  "layout",
  "smile-fill",
  "expand",
  "left-square",
  "stop-fill",
  "delete column",
  "play-square",
  "warning-circle-fill",
  "merge-cells",
  "control",
  "time-circle-fill",
  "subnode",
  "code library",
  "trademark-circle-fil",
  "rotate-left",
  "detail",
  "YUAN-circle-fill",
  "rotate-right",
  "minus-square",
  "heart-fill",
  "insert row below",
  "plus-square",
  "pie chart-circle-fil",
  "insert row above",
  "right-square",
  "dashboard-fill",
  "table",
  "project",
  "message-fill",
  "solit-cells",
  "wallet",
  "check-square-fill",
  "format painter",
  "up-square",
  "down-square-fill",
  "insert row right",
  "calculator",
  "minus-square-fill",
  "format painter-fill",
  "interation",
  "close-square-fill",
  "insert row left",
  "check-square",
  "code library-fill",
  "translate",
  "border",
  "left-square-fill",
  "delete row",
  "border-outer",
  "play-square-fill",
  "sisternode",
  "border-top",
  "up-square-fill",
  "Field-number",
  "border-bottom",
  "right-square-fill",
  "Field-String",
  "border-left",
  "plus-square-fill",
  "Function",
  "border-right",
  "account book-fill",
  "Field-time",
  "border-inner",
  "carry out-fill",
  "GIF",
  "border-verticle",
  "calendar-fill",
  "Partition",
  "border-horizontal",
  "calculator-fill",
  "index",
  "radius-bottomleft",
  "interation-fill",
  "Stored procedure",
  "radius-bottomright",
  "project-fill",
  "Field-Binary",
  "radius-upleft",
  "detail-fill",
  "Console-SQL",
  "radius-upright",
  "save-fill",
  "radius-setting",
  "wallet-fill",
  "aim",
  "add user",
  "control-fill",
  "compress",
  "delete team",
  "layout-fill",
  "expend",
  "delete user",
  "app store-fill",
  "folder-view",
  "addteam",
  "mobile-fill",
  "file-GIF",
  "user",
  "tablet-fill",
  "group",
  "team",
  "book-fill",
  "send",
  "area chart",
  "red envelope-fill",
  "Report",
  "line chart",
  "safety certificate-f",
  "View",
  "bar chart",
  "property safety-fill",
  "shortcut",
  "point map",
  "insurance-fill",
  "ungroup",
  "container",
  "security scan-fill",
  "database",
  "file-exclamation-fil",
  "sever",
  "file-add-fill",
  "mobile",
  "file-fill",
  "tablet",
  "file-excel-fill",
  "red envelope",
  "file-markdown-fill",
  "book",
  "file-text-fill",
  "file done",
  "file-ppt-fill",
  "reconciliation",
  "file-unknown-fill",
  "file -exception",
  "file-word-fill",
  "file sync",
  "file-zip-fill",
  "file search",
  "file-pdf-fill",
  "solution",
  "file-image-fill",
  "file protect",
  "diff-fill",
  "file-add",
  "file-copy-fill",
  "file-excel",
  "snippets-fill",
  "file-exclamation",
  "batch folding-fill",
  "file-pdf",
  "reconciliation-fill",
  "file-image",
  "folder-add-fill",
  "file-markdown",
  "folder-fill",
  "file-unknown",
  "folder-open-fill",
  "file-ppt",
  "database-fill",
  "file-word",
  "container-fill",
  "file",
  "sever-fill",
  "file-zip",
  "calendar-check-fill",
  "file-text",
  "image-fill",
  "file-copy",
  "id card-fill",
  "snippets",
  "credit card-fill",
  "audit",
  "fund-fill",
  "diff",
  "read-fill",
  "Batch folding",
  "contacts-fill",
  "security scan",
  "delete-fill",
  "property safety",
  "notification-fill",
  "safety certificate",
  "flag-fill",
  "insurance",
  "money collect-fill",
  "alert",
  "medicine box-fill",
  "delete",
  "rest-fill",
]
export default iconsNames